# Form implementation generated from reading ui file 'design_admin_interface.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1300, 800)
        Form.setMinimumSize(QtCore.QSize(1300, 800))
        Form.setMaximumSize(QtCore.QSize(1300, 800))
        self.label_A2 = QtWidgets.QLabel(parent=Form)
        self.label_A2.setGeometry(QtCore.QRect(710, 770, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_A2.setFont(font)
        self.label_A2.setWordWrap(True)
        self.label_A2.setObjectName("label_A2")
        self.buttonEditUs = QtWidgets.QPushButton(parent=Form)
        self.buttonEditUs.setGeometry(QtCore.QRect(1070, 650, 181, 71))
        self.buttonEditUs.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonEditUs.setObjectName("buttonEditUs")
        self.boxName = QtWidgets.QLineEdit(parent=Form)
        self.boxName.setGeometry(QtCore.QRect(1070, 580, 201, 51))
        self.boxName.setObjectName("boxName")
        self.label_B1 = QtWidgets.QLabel(parent=Form)
        self.label_B1.setGeometry(QtCore.QRect(360, 10, 81, 21))
        self.label_B1.setObjectName("label_B1")
        self.label_A1 = QtWidgets.QLabel(parent=Form)
        self.label_A1.setGeometry(QtCore.QRect(960, 0, 221, 31))
        self.label_A1.setObjectName("label_A1")
        self.boxEmail = QtWidgets.QLineEdit(parent=Form)
        self.boxEmail.setGeometry(QtCore.QRect(810, 660, 211, 51))
        self.boxEmail.setObjectName("boxEmail")
        self.label_C8 = QtWidgets.QLabel(parent=Form)
        self.label_C8.setGeometry(QtCore.QRect(1150, 550, 61, 31))
        self.label_C8.setObjectName("label_C8")
        self.label_C4 = QtWidgets.QLabel(parent=Form)
        self.label_C4.setGeometry(QtCore.QRect(890, 550, 71, 31))
        self.label_C4.setObjectName("label_C4")
        self.label_C6 = QtWidgets.QLabel(parent=Form)
        self.label_C6.setGeometry(QtCore.QRect(1130, 390, 81, 31))
        self.label_C6.setObjectName("label_C6")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 791, 321))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.boxPhone = QtWidgets.QLineEdit(parent=Form)
        self.boxPhone.setGeometry(QtCore.QRect(1070, 420, 201, 51))
        self.boxPhone.setObjectName("boxPhone")
        self.boxPassword = QtWidgets.QLineEdit(parent=Form)
        self.boxPassword.setGeometry(QtCore.QRect(820, 580, 201, 51))
        self.boxPassword.setObjectName("boxPassword")
        self.label_C5 = QtWidgets.QLabel(parent=Form)
        self.label_C5.setGeometry(QtCore.QRect(890, 630, 71, 31))
        self.label_C5.setObjectName("label_C5")
        self.scrollArea2 = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea2.setGeometry(QtCore.QRect(0, 450, 791, 321))
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName("scrollArea2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 789, 319))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_C1 = QtWidgets.QLabel(parent=Form)
        self.label_C1.setGeometry(QtCore.QRect(340, 430, 121, 21))
        self.label_C1.setObjectName("label_C1")
        self.boxLogin = QtWidgets.QLineEdit(parent=Form)
        self.boxLogin.setGeometry(QtCore.QRect(820, 500, 201, 51))
        self.boxLogin.setObjectName("boxLogin")
        self.label_C3 = QtWidgets.QLabel(parent=Form)
        self.label_C3.setGeometry(QtCore.QRect(890, 470, 91, 31))
        self.label_C3.setObjectName("label_C3")
        self.label_C7 = QtWidgets.QLabel(parent=Form)
        self.label_C7.setGeometry(QtCore.QRect(1140, 470, 61, 31))
        self.label_C7.setObjectName("label_C7")
        self.boxAge = QtWidgets.QLineEdit(parent=Form)
        self.boxAge.setGeometry(QtCore.QRect(1070, 500, 201, 51))
        self.boxAge.setObjectName("boxAge")
        self.boxID = QtWidgets.QLineEdit(parent=Form)
        self.boxID.setGeometry(QtCore.QRect(820, 420, 201, 51))
        self.boxID.setObjectName("boxID")
        self.label_C2 = QtWidgets.QLabel(parent=Form)
        self.label_C2.setGeometry(QtCore.QRect(910, 390, 31, 31))
        self.label_C2.setObjectName("label_C2")
        self.boxBarCode = QtWidgets.QLineEdit(parent=Form)
        self.boxBarCode.setGeometry(QtCore.QRect(820, 60, 201, 51))
        self.boxBarCode.setObjectName("boxBarCode")
        self.boxStatus = QtWidgets.QLineEdit(parent=Form)
        self.boxStatus.setGeometry(QtCore.QRect(1070, 60, 201, 51))
        self.boxStatus.setObjectName("boxStatus")
        self.boxIdPac = QtWidgets.QLineEdit(parent=Form)
        self.boxIdPac.setGeometry(QtCore.QRect(820, 150, 201, 51))
        self.boxIdPac.setObjectName("boxIdPac")
        self.boxCont = QtWidgets.QLineEdit(parent=Form)
        self.boxCont.setGeometry(QtCore.QRect(820, 250, 201, 51))
        self.boxCont.setObjectName("boxCont")
        self.boxWeight = QtWidgets.QLineEdit(parent=Form)
        self.boxWeight.setGeometry(QtCore.QRect(1070, 150, 201, 51))
        self.boxWeight.setObjectName("boxWeight")
        self.label_B2 = QtWidgets.QLabel(parent=Form)
        self.label_B2.setGeometry(QtCore.QRect(890, 30, 81, 31))
        self.label_B2.setObjectName("label_B2")
        self.label_B3 = QtWidgets.QLabel(parent=Form)
        self.label_B3.setGeometry(QtCore.QRect(910, 120, 31, 31))
        self.label_B3.setObjectName("label_B3")
        self.label_B4 = QtWidgets.QLabel(parent=Form)
        self.label_B4.setGeometry(QtCore.QRect(870, 220, 131, 31))
        self.label_B4.setObjectName("label_B4")
        self.label_B5 = QtWidgets.QLabel(parent=Form)
        self.label_B5.setGeometry(QtCore.QRect(1140, 30, 81, 31))
        self.label_B5.setObjectName("label_B5")
        self.label_B6 = QtWidgets.QLabel(parent=Form)
        self.label_B6.setGeometry(QtCore.QRect(1110, 120, 131, 31))
        self.label_B6.setObjectName("label_B6")
        self.buttonEditPac = QtWidgets.QPushButton(parent=Form)
        self.buttonEditPac.setGeometry(QtCore.QRect(1080, 240, 181, 71))
        self.buttonEditPac.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonEditPac.setObjectName("buttonEditPac")
        self.buttonDelUs = QtWidgets.QPushButton(parent=Form)
        self.buttonDelUs.setGeometry(QtCore.QRect(1070, 730, 181, 41))
        self.buttonDelUs.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonDelUs.setObjectName("buttonDelUs")
        self.buttonDelPac = QtWidgets.QPushButton(parent=Form)
        self.buttonDelPac.setGeometry(QtCore.QRect(1080, 320, 181, 41))
        self.buttonDelPac.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonDelPac.setObjectName("buttonDelPac")
        self.label_A3 = QtWidgets.QLabel(parent=Form)
        self.label_A3.setGeometry(QtCore.QRect(530, 0, 221, 31))
        self.label_A3.setObjectName("label_A3")
        self.label_A4 = QtWidgets.QLabel(parent=Form)
        self.label_A4.setGeometry(QtCore.QRect(510, 400, 221, 31))
        self.label_A4.setObjectName("label_A4")
        self.buttonAddPac = QtWidgets.QPushButton(parent=Form)
        self.buttonAddPac.setGeometry(QtCore.QRect(830, 320, 181, 41))
        self.buttonAddPac.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonAddPac.setObjectName("buttonAddPac")
        self.buttonAddUs = QtWidgets.QPushButton(parent=Form)
        self.buttonAddUs.setGeometry(QtCore.QRect(830, 730, 181, 41))
        self.buttonAddUs.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:10px;\n"
"border: 2px solid white;\n"
"color: white\n"
"}")
        self.buttonAddUs.setObjectName("buttonAddUs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Личный кабинет"))
        self.label_A2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">sys</span></p></body></html>"))
        self.buttonEditUs.setText(_translate("Form", "Сохранить изменения"))
        self.label_B1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Заказы</span></p></body></html>"))
        self.label_A1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Редактировать данные</span></p></body></html>"))
        self.label_C8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">ФИО</span></p></body></html>"))
        self.label_C4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Пароль</span></p></body></html>"))
        self.label_C6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Телефон</span></p></body></html>"))
        self.label_C5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Email</span></p></body></html>"))
        self.label_C1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Пользователи</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_C3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Логин</span></p></body></html>"))
        self.label_C7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Возраст</span></p></body></html>"))
        self.label_C2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">id</span></p></body></html>"))
        self.label_B2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Баркод</span></p></body></html>"))
        self.label_B3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">id</span></p></body></html>"))
        self.label_B4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Содержимое </span></p></body></html>"))
        self.label_B5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Статус</span></p></body></html>"))
        self.label_B6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Вес (в граммах)</span></p></body></html>"))
        self.buttonEditPac.setText(_translate("Form", "Сохранить изменения"))
        self.buttonDelUs.setText(_translate("Form", "Удалить пользователя"))
        self.buttonDelPac.setText(_translate("Form", "Удалить посылку"))
        self.label_A3.setText(_translate("Form", "<html><head/><body><p/><p><br/></p></body></html>"))
        self.label_A4.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAddPac.setText(_translate("Form", "Добавить посылку"))
        self.buttonAddUs.setText(_translate("Form", "Добавить пользователя"))
